server:
  port: 8084
 
spring: 
  application:
    name: API-GATEWAY
  
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri : lb://USER-SERVICE
          predicates:
            - Path=/users/**
            
        - id: BLOG-SERVICE
          uri : lb://BLOG-SERVICE
          predicates:
            - Path=/blogs/**
            
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /BLOG-SERVICE/v3/api-docs
        name: BLOG SERVICE
      - url: /USER-SERVICE/v3/api-docs
        name: USER SERVICE
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8083/eureka  